### PR TITLE
Add neovim check

### PR DESCRIPTION
**Pull request by ahmedelgabri**
Neovim removed `has('gui_running')` https://github.com/neovim/neovim/wiki/Following-HEAD#20160204 so this will fix this issue by add `has('nvim')` to all the checks that uses `has('gui_running')`

### CODE REVIEW

**Comment by chemzqm** [comment]
:+1:  user should have true color enabled to use this.

**Comment by ap** [comment]
Thanks. I haven’t applied this yet because I’m not a NeoVim user so I had to do my homework first to see if it is correct. Based on my research, I believe this patch is correct but insufficient.

Currently the plugin assumes that it’s either running with a GUI or on a terminal, and it also assumes that GUI means truecolor and terminal means a 256 colour palette. But NeoVim has a client-server model where multiple UIs can be attached to the same server, and scripts runs on the server. So it seems necessary to me to change the plugin so that detecting NeoVim voids these assumptions, i.e. the plugin will create highlights with both truecolor and indexed colours. Then each client can use the type of colour it supports.

Is that correct?

**Comment by chemzqm** [comment]
@ap you're right, I can confirm that

**Comment by ahmedelgabri** [comment]
@ap I think you are right.

**Comment by ap** [comment]
I’ve just pushed [the `neovim` branch](/ap/vim-css-color/tree/neovim) that does this. Please test this and let me know whether it does the right thing under all the possible configurations:

* Neovim in terminal with 256 colours
* Neovim in terminal with truecolor support enabled
* Neovim GUI
* Even with several different kinds of client connected to a server at once

**Comment by ap** [comment]
OK, I’ve verified it works in the terminal (and also in Vim, both terminal and GUI). However, because I’m stuck on OS&#160;X&#160;10.7, I can install neither a terminal with truecolor support nor a Neovim GUI, so I cannot test either of these myself at this time.

Anyone?

**Comment by jalvesaq** [comment]
There is no need to check `has("nvim")` because with Neovim `&t_Co==256`. What should be checked is whether Neovim is displaying true colors or not. This seems to be enough:

```diff
diff --git a/autoload/css_color.vim b/autoload/css_color.vim
index 97b1064..44aeab7 100644
--- a/autoload/css_color.vim
+++ b/autoload/css_color.vim
@@ -42,7 +42,7 @@ for i in range(0, 255)
 	let s:hex[ printf( '%02x', i ) ] = i
 endfor
 
-if has('gui_running')
+if has('gui_running') || $NVIM_TUI_ENABLE_TRUE_COLOR == 1
 	let s:is_gui = 1
 else
 	let s:is_gui = 0
```

**Comment by jalvesaq** [comment]
Note: I tested on Linux (Ubuntu 15.10) with R file type. It tested it with gnome-terminal, xterm and st.

**Comment by ap** [comment]
> There is no need to check `has("nvim")` because with Neovim `&t_Co==256`.

Even when initially started from a 16-colour terminal…?

> This seems to be enough:

That check seems completely wrong to me.

What happens if you first start a Neovim server instance *without* `NVIM_TUI_ENABLE_TRUE_COLOR`, then connect a `NVIM_TUI_ENABLE_TRUE_COLOR=1` client to it? If I am reasoning correctly, that client would only get to display 256-colour highlights, even though it has truecolor support.

So it seems to me that the value of `NVIM_TUI_ENABLE_TRUE_COLOR` should be irrelevant to the plugin. That was my conclusion previously: that on Neovim, the plugin should always create set up both the truecolor and the terminal palette value in highlights, so that the client can pick the best one it supports.

Question, did I miss something?

**Comment by ap** [comment]
> Note: I tested on Linux (Ubuntu 15.10) with R file type. It tested it with gnome-terminal, xterm and st.

What specifically did you test?

**Comment by jalvesaq** [comment]
On Linux console, Neovim wrongly sets t_Co = 256.
Sorry, I had not thought about the case you mentioned (starting Neovim in a way and then connecting to another client). And you are right: in a terminal emulator Neovim picks the nearest color from the 256 color palette while GVim displays the real color.

**Comment by jalvesaq** [comment]
After your comment, I'm using the following code:
```r
plot(c(1, 2), c(1, 2), pch =20, cex = 4,
     col = c("#123456", "#123457"))
```
And gcolor2 to pick the background color. Neovim-Qt works like Gvim, and displays the real color.

**Comment by jalvesaq** [comment]
@ap I tested the [neovim branch](https://github.com/ap/vim-css-color/tree/neovim). Both Vim and Neovim in gnome-terminal display the color `#005f5f`, while both Neovim-Qt and Gvim display the true colors (`#123456` and `#123457`).

**Comment by ap** [comment]
Do you have a terminal with truecolor support to test on? That’s the last case missing confirmation.

**Comment by jalvesaq** [comment]
I was testing inside tmux 2.1. When running nvim in gnome-terminal without tmux, I actually get true colors:

gnome-terminal_nvim

**Comment by ap** [comment]
Well then, hooray. :+1:

I’ve merged the branch into `master`. Thank you @ahmedelgabri for the patch.

**Comment by ahmedelgabri** [comment]
@ap sorry I was on (a disconnected) vacation so I couldn't test, thanks for merging the PR :+1:

**Comment by ap** [comment]
Enjoy. :smile:

**Pull request closed without merging**
