### PR TITLE
Making it compatible with vim-styled-components

### PR DESCRIPTION
**Pull request by sassanh**

### CODE REVIEW

**Comment by sassanh** [comment]
Without this patch this is the value of `b:css_color_grp`:

['xmlComment', 'xmlCommentPart', 'xmlString', 'javaScriptComment', 'javaScriptLineComment', 'javaScriptStringS', 'javaScriptStringD', 'jsComment', 'jsSt
ring', 'jsTemplateString', 'jsObjectKeyString', 'jsObjectStringKey', 'jsClassStringKey', 'cssMediaBlock', 'cssFunction', 'cssDefinition', 'cssAttrRegion
', 'cssComment', 'javaScriptComment', 'javaScriptLineComment', 'javaScriptStringS', 'javaScriptStringD', 'jsComment', 'jsString', 'jsTemplateString', 'j
sObjectKeyString', 'jsObjectStringKey', 'jsClassStringKey', 'cssMediaBlock', 'cssFunction', 'cssDefinition', 'cssAttrRegion', 'cssComment', 'xmlComment'
, 'xmlCommentPart', 'xmlString', 'javaScriptComment', 'javaScriptLineComment', 'javaScriptStringS', 'javaScriptStringD', 'jsComment', 'jsString', 'jsTem
plateString', 'jsObjectKeyString', 'jsObjectStringKey', 'jsClassStringKey', 'cssMediaBlock', 'cssFunction', 'cssDefinition', 'cssAttrRegion', 'cssCommen
t', 'javaScriptComment', 'javaScriptLineComment', 'javaScriptStringS', 'javaScriptStringD', 'jsComment', 'jsString', 'jsTemplateString', 'jsObjectKeyStr
ing', 'jsObjectStringKey', 'jsClassStringKey', 'cssMediaBlock', 'cssFunction', 'cssDefinition', 'cssAttrRegion', 'cssComment']

With this patch, it also has `cssColor`.

**Comment by ap** [comment]
OK… so the acconglomeration of highlight groups is doing its job. And what’s going on is that styled-components includes the CSS syntax into the Javascript one, but does it by defining multiple `cssCustomFoobar` highlight groups mirroring a corresponding `cssFoobar` highlight group from the CSS syntax – including the ones css-color needs, `cssMediaBlock` and `cssAttrRegion`.

So adding `cssColor` is not enough. It works around the most common case but leaves out `rgb()` and `hsl()` support. I have to add `cssCustomMediaBlock` and `cssCustomAttrRegion` instead.

And I have to check to make sure that the `cssFunction` in css-color’s list of highlight groups in `after/syntax/css.vim` is actually useful. After this exercise I believe it to be useless. But I am also considering adding a hack to make it useful (and submitting that as a patch upstream), and then replacing `cssMediaBlock` and `cssAttrRegion` in that list with just `cssColor`. That would also confer proper colouring to styled-component as a side effect.

**Comment by sassanh** [comment]
OK, thanks for info, looking forward for new updates then.

**Comment by silicakes** [comment]
Hi, Any news on this?

**Pull request closed without merging**
