### PR TITLE
add support for cfg files

### PR DESCRIPTION
**Pull request by maujim**

### CODE REVIEW

**Comment by maujim** [comment]
I saw lots of issues asking for commands to add support for different filetypes. I wrote a small script to parse `$VIMRUNTIME/syntax/[filetype].vim` and return the appropriate parameters to pass to `css_color#init()`. 

I'm happy to share it but I saw that you don't want to add anything to the README and prefer a proper Vimdoc file. Thus, I'm not sure where to share it.

**Comment by ap** [comment]
Pushed as c2589682e3208acb04e2cdb610ae1120b5f8069a. Thank you for the patch!

I’m very curious about the script and how you approached that task, given that [I’ve been meaning to write the same thing myself](/ap/vim-css-color/issues/85#issuecomment-323551192), but it’s probably not going to fit that plan as-is. So sharing it any way that works for you would be fine – dumping it anywhere in the repository, maybe on a branch, and sending a PR, or putting it in a Gist, or pasting it in a code section in an issue comment, or… whatever works for you. If I do end up using it, I’ll commit it under your name no matter what, anyway (unless you wish otherwise, of course). So it really doesn’t matter which way you share it – feel free to pick whatever you prefer.

**Comment by maujim** [comment]
Turns out my understanding of vim syntax highlighting was not as proficient as I thought. Upon further testing, my script doesn't actually work :disappointed:

**Comment by ap** [comment]
And here I was hoping someone else had already done the hard work for me. 🙂

It’s harder than it looks. I’ve been thinking on it ever since it occurred to me that it was possible, but every time I’ve attempted it I’ve hit another snag just big enough that I wander off and do something else. I’m convinced it’s doable – it will just be somewhat involved and complicated, and I haven’t had the perseverance to see it through to conclusion. I was hoping I could be lazy and ride someone else’s coattails. 🙂

**Pull request closed without merging**
